spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://rm-wz9u841d66c0td1fq6o.mysql.rds.aliyuncs.com:3306/wishlist?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: wishlist
        password: ENC(lNUcvnJHALkQdC51gY+bWE7UJ0ar7b21LW3HTNftCPY=)
mybatis:
    mapper-locations: ["classpath:mapper/*Mapper.xml", "classpath:mapper/**/*Mapper.xml"]
    config-location: classpath:mapper/config/sqlMapConfig.xml
app:
    appId: "wxa823794835f994b3"
    appSecret: "1e0d9911438978e850061262a1c58889"
info:
    github: https://github.com/abigail830/wish-list
    jitpack: https://jitpack.io/#abigail830/wish-list



