---
- hosts: centOS7
  remote_user: root
  vars:
    version: 1.0.1
  tasks:
  - name: download package from nexus
    maven_artifact:
      group_id: 'com.github.abigail830'
      artifact_id: 'wish-list'
      version: "{{version}}"
      repository_url: 'http://nexus.saraqian.cn/nexus/content/repositories/releases/'
      dest: /var/www/wish-list-1/wish-list-{{version}}.jar
      mode: 0744

  - name: Remove existing softlink
    file:
      state: absent
      path: /var/www/wish-list-1/wish-list.jar

  - name: Create new softlink to deploy file
    file:
      src: /var/www/wish-list-1/wish-list-{{version}}.jar
      dest: /var/www/wish-list-1/wish-list.jar
      state: link
      mode: 0744

  - name: Stop current process
    command: /var/www/wish-list-1/stop.sh

  - name: Start new process
    command: /var/www/wish-list-1/start.sh

